ANDROID: GKI: drm/mediatek: do not use namespace DRM_MTK_HDMI
From [1], modules that make use of symbols exported into
namespaces, are required to import the namespace. Otherwise
the kernel will, depending on its configuration, reject
loading the module or warn about a missing import.

Currently, Bazel build system does not handles it correctly,
giving errors like:

	drivers/gpu/drm/mediatek/mtk_hdmi_common.mod.c:15:43: error: expected ')'
	   15 | KSYMTAB_FUNC(mtk_hdmi_get_ncts, "_gpl", ""DRM_MTK_HDMI"");
	      |                                           ^
	drivers/gpu/drm/mediatek/mtk_hdmi_common.mod.c:15:1: note: to match this '('
	   15 | KSYMTAB_FUNC(mtk_hdmi_get_ncts, "_gpl", ""DRM_MTK_HDMI"");
	      | ^
	/data/vsatoes/aiot-rita-14-kernel-6.12-new/common/include/linux/export-internal.h:62:37: note: expanded from macro 'KSYMTAB_FUNC'
	   62 | #define KSYMTAB_FUNC(name, sec, ns)     __KSYMTAB(name, KSYM_FUNC(name), sec, ns)
	      |                                         ^
	/data/vsatoes/aiot-rita-14-kernel-6.12-new/common/include/linux/export-internal.h:41:5:	note: expanded from macro '__KSYMTAB'
	   41 |         asm("   .section \"__ksymtab_strings\",\"aMS\",%progbits,1"     "\n"    \
	      |            ^

To avoid this, remove namespace DRM_MTK_HDMI.

[1]: https://docs.kernel.org/core-api/symbol-namespaces.html

Signed-off-by: Vitor Sato Eschholz <vsatoes@baylibre.com>