MA-7902 Support XTS-AES-NEON
Enable ARM_CRYPTO to support XTS-AES-NEON
crypto driver in kernel.

This patch fixed the CTS error:
android.security.cts.EncryptionTest#testConfig FAIL
junit.framework.AssertionFailedError: /proc/crypto is missing
xts-aes-neon (or xts-aes-neonbs)

Change-Id: I917e32226f3a80166fa68949bf2fd35fdd8737d4
Signed-off-by: Wang Haoran <Haoran.Wang@freescale.com>