LF-7677 usb: gadget: Assign an unique name for each configfs driver
When use configfs to attach more than one gadget.

Error: Driver 'configfs-gadget' is already registered, aborting...

	UDC core: g1: driver registration failed: -16

The problem is that when creating multiple gadgets with configfs and
binding them to different UDCs, the UDC drivers have the same name
"configfs-gadget". Because of the addition of the "gadget" bus, naming
conflicts will occur when more than one UDC drivers registered to the
bus.

It's not an isolated case, this patch refers to the commit f2d8c2606825
("usb: gadget: Fix non-unique driver names in raw-gadget driver").
Each configfs-gadget driver will be assigned a unique name
"configfs-gadget.N", with a different value of N for each driver
instance.

Fixes: fc274c1e9973 ("USB: gadget: Add a new bus for gadgets")

Signed-off-by: Rondreis <linhaoguo86@gmail.com>
Signed-off-by: Frank Li <Frank.Li@nxp.com>