arm64: boundary_defconfig: initial addition
remove MXC_GPU_VIV
add missing clk_pwm option
remove deprecated fw user helper fallback
add FSL_OTP driver
add SNVS reboot communication driver
add usb functionfs gadget
   So adbd can be used even on Linux kernel.
enable i.MX8MM and i.MX8QP platforms
add missing SPI_IMX driver
boundary_defconfig: add SPI to CAN drivers for evaluation
arm64: boundary: savedefconfig + quick update
arm64: boundary_defconfig: remove malone/windsor vpu to fix build
squash: boundary_defconfig: remove dsp sound driver
arm64: boundary_defconfig: add missing ubuntu/docker configurations
arm64: boundary_defconfig: add tc358840 module
arm64: boundary_defconfig: make eqos built-in
arm64: boundary_defconfig: add missing 8mp drivers
arm64: boundary_defconfig: add missing audio drivers
arm64: boundary_defconfig: add PCA9450 PMIC driver
arm64: boundary_defconfig: align debug features with android config
arm64: boundary_defconfig: fix PCIe configuration
arm64: boundary_defconfig: add missing thermal driver
arm64: boundary_defconfig: enable ILI2010X driver
arm64: boundary_defconfig: add bq2589x charger driver
arm64: boundary_defconfig: add core options
arm64: boundary_defconfig: add HIDDEV driver
arm64: boundary_defconfig: add gpio fan driver
arm64: boundary_defconfig: add alliedvision camera support
arm64: boundary_defconfig: add imx8 ddr pmu
arm64: boundary_defconfig: add IP_SET config
arm64: boundary_defconfig: enable adp1650 driver
arm64: boundary_defconfig: enable max77823 driver
arm64: boundary_defconfig: add usb serial and ftdi modules
arm64: boundary_defconfig: add tab drivers
arm64: boundary_defconfig: add snvs pwrkey
arm64: boundary_defconfig: add missing dmabuf options
arm64: boundary_defconfig: add missing HDMI audio driver
arm64: boundary_defconfig: switch max77823 to module
arm64: boundary_defconfig: fix switch max77823 to module
arm64: boundary_defconfig: add SAS driver
arm64: boundary_defconfig: add TPM pwm driver
arm64: boundary_defconfig: switch hciuart to module

- And add BCM driver too for LWB5+ module
arm64: boundary_defconfig: enable DM_CRYPT option
arm64: boundary_defconfig: run savedefconfig

Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

add CONFIG_TOUCHSCREEN_GOODIX=m
add ft5x06 touchscreen, SN65DSI83
increase to CONFIG_LOG_BUF_SHIFT=16
make OV5640_MIPI_V2 a module
add CONFIG_BLK_DEV_NVME=m
add CONFIG_TOUCHSCREEN_SITRONIX_I2C_TOUCH
REGULATOR_PF8X00/IMX_LCDIF_CORE/DRM_SEC_MIPI_DSIM/DRM_IMX_SEC_DSIM
remove CONFIG_ARCH_FSL_IMX8QXP
arm64: boundary_defconfig: use CONFIG_DRM_IMX_SEC_DSIM=y instead of module
arm64: configs: boundary_defconfig: add CONFIG_MXC_VPU_LEGACY
arm64: configs: boundary_defconfig: add CONFIG_ION_CMA_HEAP
arm64: boundary_defconfig: add CONFIG_CRYPTO_DEV_FSL_CAAM
arm64: boundary_defconfig: add CONFIG_SERIAL_SC16IS7XX=m
arm64: boundary_defconfig: add CONFIG_TOUCHSCREEN_SILEAD
arm64: configs: boundary_defconfig: add CONFIG_LEDS_TRIGGER_TIMER
arm64: boundary_defconfig: add CONFIG_LT8912
arm64: boundary_defconfig: add CONFIG_TOUCHSCREEN_EXC3000=m
arm64: configs: boundary_defconfig: add CONFIG_ARCH_FSL_IMX8MN=y
squash CONFIG_ENCX24J600=m, boundary_defconfig
arm64: configs: boundary_defconfig: add CONFIG_ENCX24J600=m
arm64: boundary_defconfig: add CONFIG_RTC_DRV_RV3028=y
arm64: boundary_defconfig: add CONFIG_REGULATOR_FAN53555
arm64: boundary_defconfig: add CONFIG_VIDEO_TC358743
arm64: boundary_defconfig: CONFIG_EXTRA_FIRMWARE for sdma
arm64: boundary_defconfig: add CONFIG_SPI_SC18IS602=y for i2c SPI bus support
arm64: boundary_defconfig: add CONFIG_PINCTRL_IMX8MP/CONFIG_CLK_IMX8MP
arm64: boundary_defconfig: add CONFIG_MFD_IMX_AUDIOMIX for i.MX8MP
arm64: boundary_defconfig: CONFIG_IMX_LCDIFV3_CORE=y for i.MX8MP
arm64: boundary_defconfig: add LVDS support for imx8mp
arm64: boundary_defconfig: add CONFIG_USB_CC_TUSB320=y
arm64: boundary_defconfig: use CONFIG_TYPEC_HD3SS3220=y instead of CONFIG_USB_CC_TUSB320=y
arm64: boundary_defconfig: add CONFIG_LAN743X=m, CONFIG_SERIAL_MAX310X=m
arm64: boundary_defconfig: add CONFIG_EXTCON_USBC_TUSB320=y
arm64: boundary_defconfig: add CONFIG_TI_ADS7924 adc converter
arm64: boundary_defconfig: add CONFIG_VIDEO_OV5640=m
arm64: boundary_defconfig: remove CONFIG_ATH10K

We build QCA6174 externally and selecting CONFIG_ATH10K interfers with that.

arm64: boundary_defconfig: add CONFIG_DRM_PANEL_COMMON
arm64: boundary_defconfig: remove CONFIG_DRM_PANEL_SIMPLE/CONFIG_SN65DSI83, use CONFIG_DRM_PANEL_COMMON instead
arm64: boundary_defconfig: add CONFIG_LEDS_LP5523=m
arm64: boundary_defconfig: add CONFIG_MEDIA_PLATFORM_SUPPORT=y
arm64: boundary_defconfig: add CONFIG_DEBUG_FS=y
arm64: boundary_defconfig: remove CONFIG_PCI_HISI/CONFIG_PCIE_KIRIN/CONFIG_PCIE_LAYERSCAPE_GEN4
arm64: boundary_defconfig: add CONFIG_CAN_MCP251XFD=m
arm64: boundary_defconfig: add CONFIG_LEDS_LP55XX_COMMON=m
arm64: boundary_defconfig: add CONFIG_CHARGER_MAX77975=y
arm64: boundary_defconfig: add CONFIG_BACKLIGHT_BD2606 for panel-lxd-m8509a
arm64: boundary_defconfig: add CONFIG_DRM_CDNS_HDCP
arm64: boundary_defconfig: add CONFIG_BACKLIGHT_CLASS_DEVICE
arm64: boundary_defconfig: add CONFIG_FB
arm64: boundary_defconfig: remove CONFIG_SERIAL_AMBA_PL011
arm64: boundary_defconfig: add CONFIG_BONDING=m
arm64: boundary_defconfig: add CONFIG_TOUCHSCREEN_ATMEL_MXT=m
arm64: boundary_defconfig: re-add GPIO_SYSFS
arm64: boundary_defconfig: add 8ULP support
arm64: boundary_defconfig: add CONFIG_INPUT_DRV260X_HAPTICS=m
arm64: boundary_defconfig: add CONFIG_IMX7ULP_WDT
arm64: boundary_defconfig: add CONFIG_I2C_MUX_PINCTRL
arm64: boundary_defconfig: add CONFIG_SND_SOC_IMX_PCM512X=m
arm64: boundary_defconfig: CONFIG_CFG80211=m so that laird module can be built externally
arm64: boundary_defconfig: switch to fsl-asoc-card to support wm8962/wm8960 with same driver
arm64: boundary_defconfig: add CONFIG_IMX8MM_LCDIF_CORE=y
arm64: boundary_defconfig: add CONFIG_PINCTRL_MCP23S08=y
arm64: boundary_defconfig: add CONFIG_VIDEO_OV5647=m
arm64: boundary_defconfig: add CONFIG_PHY_FSL_IMX8M_PCIE=y
arm64: boundary_defconfig: add CONFIG_MAX1363=m
arm64: boundary_defconfig: re-add CONFIG_VIDEO_TC358840, CONFIG_CRYPTO_SM4_GENERIC

Signed-off-by: Troy Kisky <troy.kisky@boundarydevices.com>

add options to comply with Debian requirements
add squashfs xz compression, needed by snappy daemon
add configs for Docker
add CONFIG_CAN_MCP251X
add CONFIG_EEPROM_AT24=m, AT24C... I2C eeprom support
arm64: boundary_defconfig: set CONFIG_IMX8MM_THERMAL=y
arm64: boundary_defconfig: set CONFIG_SYSTEM_BLACKLIST_KEYRING=y , Ubuntu requirement
arm64: boundary_defconfig: add USB_NET_QMI_WWAN=m and USB_SERIAL_OPTION=m, support for Quectel EC25-A cell modem
arm64: boundary_defconfig: add CONFIG_IP_SCTP=m, Stream Control Transmission Protocol
arm64: boundary_defconfig: set CONFIG_R8188EU=m
arm64: boundary_defconfig: added CRYPTO_USER_API's for some bluetooth devices
arm64: boundary_defconfig: enable a few network cards

Signed-off-by: Laci Tele <laci@boundarydevices.com>

arm64: boundary_defconfig: add wiegand driver
boundary_defconfig: add CONFIG_KPROBES=y

Needed for lttng-modules in yocto hardknott + 5.10 kernel, as per the
compilation error:

LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0

Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>

arm64: boundary_defconfig: enable brcmfmac module
  Taken from boundary-imx_5.15.y branch
arm64: boundary_defconfig: add CONFIG_SQUASHFS_LZO
  Needed for snapd

Signed-off-by: Simon Gaynor <simon.gaynor@lairdconnect.com>