MA-20999-5 defconfig: Fix build error
Fix below build error:

In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/drivers/crypto/hisilicon/hpre/hpre_crypto.c:3:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/crypto/akcipher.h:10:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/crypto.h:20:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/slab.h:15:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/gfp.h:7:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/mmzone.h:8:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/spinlock.h:63:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/lockdep.h:14:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/smp.h:13:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/cpumask.h:12:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/bitmap.h:11:
In file included from /home/ssd-1/imx_android-13.0/vendor/nxp-opensource/kernel_imx/include/linux/string.h:253:
include/linux/fortify-string.h:404:4: error: call to __write_overflow_field declared with 'warning' attribute: detected write beyond size of field (1st parameter); maybe use struct_group()? [-Werror,-Wattribute-warning]
                        __write_overflow_field(p_size_field, size);

hpre_crypto.c is not being used, so remove it.

Change-Id: Ic3c6ee4ce3b4e145331388b57ff200aa5b5cc207
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>