LF-13036: media: imx8-isi: Fix potential build error when ISI m2m is disabled
Fix potential build error when ISI m2m is disabled, log as bellow:

drivers/media/platform/nxp/imx8-isi/imx8-isi-core.c: In function ‘mxc_isi_pm_suspend’:
drivers/media/platform/nxp/imx8-isi/imx8-isi-core.c:359:17: error: implicit declaration of function ‘mxc_isi_m2m_suspend’; did you mean ‘mxc_isi_pm_suspend’? [-Werror=implicit-function-declaration]
              mxc_isi_m2m_suspend(pipe);
              ^~~~~~~~~~~~~~~~~~~
              mxc_isi_pm_suspend
drivers/media/platform/nxp/imx8-isi/imx8-isi-core.c: In function ‘mxc_isi_pm_resume’:
drivers/media/platform/nxp/imx8-isi/imx8-isi-core.c:390:23: error: implicit declaration of function ‘mxc_isi_m2m_resume’; did you mean ‘mxc_isi_pm_resume’? [-Werror=implicit-function-declaration]
              ret = mxc_isi_m2m_resume(pipe);
                    ^~~~~~~~~~~~~~~~~~
                    mxc_isi_pm_resume
cc1: some warnings being treated as errors

Fixes: a84383ad339c ("LF-13013-02: media: imx8-isi: Add suspend/resume support for ISI m2m")

Signed-off-by: Guoniu.zhou <guoniu.zhou@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>