LF-1011-3 clk: imx8mm: fix build due to the removal of uart_clk_ids
API was changed since
    4eeaaeb160bf ("clk: imx: enable the earlycon uart clocks by parsing from dt")

Error log:
In file included from ../include/linux/clk.h:13,
                 from ../drivers/clk/imx/clk-imx8mm.c:7:
../drivers/clk/imx/clk-imx8mm.c: In function ‘imx8mm_clocks_probe’:
../drivers/clk/imx/clk-imx8mm.c:632:29: error: ‘uart_clk_ids’ undeclared (first use in this function)
  632 |  for (i = 0; i < ARRAY_SIZE(uart_clk_ids); i++) {

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>