serial: imx: Fix the compilation error
As per commit 1c06bde643d0 ("Allowing UART DMA to be configured on i.MX53")
make changes to fix the compilation error.

drivers/tty/serial/imx.c: In function ‘imx_uart_set_termios’:
drivers/tty/serial/imx.c:1621:8: error: implicit declaration of function ‘is_imx6q_uart’ [-Werror=implicit-function-declaration]
    if (is_imx6q_uart(sport) && !uart_console(port)
        ^~~~~~~~~~~~~

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>