MA-18920 soc: imx: Fix redefinition of 'init_module' build error
Revert four patches to fix below build error:
drivers/soc/imx/soc-imx8m.c:324:1: error: redefinition of 'init_module'
    module_platform_driver(imx8_soc_info_driver);
...
drivers/soc/imx/soc-imx8m.c:314:1: note: previous definition is here
    device_initcall(imx8_soc_init);

WARNING: modpost: drivers/soc/imx/soc-imx8m.o(.text+0x2f4):
Section mismatch in reference from the function imx8_soc_info() to the function .init.text:imx8mq_noc_init()
The function imx8_soc_info() references
the function __init imx8mq_noc_init().
This is often because imx8_soc_info lacks a __init

Revert "soc: imx8m: change to use platform driver"
This reverts commit 6375d33dce9af7567e197f84b698fb268888eada.

Revert "dt-bindings: soc: imx8m: add DT Binding doc for soc unique ID"
This reverts commit 3fffe76bdaf0d6017a00e6817563003dcfa28645.

Revert "arm64: dts: imx8m: add SoC ID compatible"
This reverts commit 7ca3bce857b5877d281167f75ae811cac8978289.

Revert "arm64: dts: imx8m: add NVMEM provider and consumer to read soc unique ID"
This reverts commit 2007d101d60c698ae28226a2b5a6a998a2067010.

Change-Id: I947ebfdf93b00cb44a23c7db5ee1b0e3e8396f7c