MA-19286-9 Disable unused config ACPI_MDIO and FSL_DPAA2_ETH
Disable these two configs to avoid build error:
  drivers/net/mdio/acpi_mdio.c:13:10: fatal error: 'linux/fwnode_mdio.h' file not found
  drivers/net/ethernet/freescale/dpaa2/dpaa2-mac.c:290:12: error:
    implicit declaration of function 'fwnode_mdio_find_device'

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: Ie02f46182954d5748cba047cec1837103eefd139