arm: boundary_defconfig: initial addition
fix SPI NOR configuration
add CONFIG_DVI_TFP410 for nitrogen6sx
add CONFIG_DMA_CMA
add CONFIG_MXC_HDMI_CSI2_TC358743=m
add CONFIG_DRM_ANX78XX=m
add CONFIG_SND_SOC_IMX_WM5102=m
add CONFIG_SND_SOC_IMX_WM8960
add CONFIG_ATH9K
add CONFIG_TOUCHSCREEN_GSLX680
add CONFIG_TOUCHSCREEN_GOODIX
make all touchscreens modules
add CONFIG_CAN_MCP251X
make CONFIG_KEYBOARD_GPIO a module
new tw686x driver
add CONFIG_MXC_HDMI_CEC
add CONFIG_POWER_RESET_GPIO (insp/mcs)
ubuntu changes
ath9k pcie does not have rfkill gpio
add CONFIG_TC358743_AUDIO
add CONFIG_LEDS_PWM
add CONFIG_USB_XHCI_HCD
add CONFIG_TOUCHSCREEN_ATMEL_MXT
add CONFIG_TOUCHSCREEN_AR1010_UART
add CONFIG_SERIAL_XR20M117X=m
add CONFIG_APDS9300=m
build GPU externally
add CONFIG_SERIAL_GPS_MAX7W for i2c GPS support
add MC13892 support for nitrogen51_vm
add imx51 support
add CONFIG_BACKLIGHT_LP8860
add imx51 support changes for 4.1
add CONFIG_TOUCHSCREEN_MC13783
add CONFIG_I2C_IMX_HS
add CONFIG_MXC_MMA8x5x=m
add CONFIG_I2C_MUX_PINCTRL
add CONFIG_ISL28022_ADC
add CONFIG_ISL76534=m
add display ST7789V support
add I2C_MUX_PCA954x/mipi dsi
add CONFIG_KEYBOARD_IMX=m
add CONFIG_DUMMY_I2C_DEVICE=m
add CONFIG_TOUCHSCREEN_SILEAD=m
add CONFIG_BRIDGE, needed for bluetooth PAN
make hdmi audio a modules, CONFIG_SND_SOC_IMX_HDMI=m
add CONFIG_TOUCHSCREEN_CYPRESS_CYTTSP5=m
add CONFIG_TOUCHSCREEN_EXC3000=m
remove CONFIG_FB_MXC_MIPI_RM68200
add CONFIG_TEE/CONFIG_OPTEE
boundary_defconfig: add CONFIG_WIEGAND=m
arm: configs: boundary_defconfig: add CONFIG_SOC_IMX6ULL
arm: configs: boundary_defconfig: add CONFIG_GPIO_PCA953X
arm: configs: boundary_defconfig: add CONFIG_DEBUG_FS
arm: boundary_defconfig: add CONFIG_RTC_DRV_RV3028
arm: boundary_defconfig: add CONFIG_ARM_IMX7D_CPUFREQ=y
arm: boundary_defconfig: CONFIG_EXTRA_FIRMWARE
arm: configs: boundary_defconfig: add CONFIG_TC358778
arm: boundary_defconfig: add CONFIG_BACKLIGHT_CLASS_DEVICE=y
arm: configs: boundary_defconfig: s/CONFIG_PWM_IMX/CONFIG_PWM_IMX27/
squash arm: dts: configs: boundary_defconfig: make savedefconfig + LOGO
arm: boundary_defconfig: add CONFIG_NVMEM_IMX_OCOTP
arm: configs: boundary_defconfig: add CONFIG_BT_HCIUART_QCA=y
arm: boundary_defconfig: add CONFIG_GPIO_MXC=y
arm: boundary_defconfig: add CONFIG_MEDIA_PLATFORM_SUPPORT/CONFIG_DEUG_FS
arm: boundary_defconfig: add CONFIG_BLK_DEV_NVME=m
boundary_defconfig: add CONFIG_I2C_MUX=y/CONFIG_I2C_MUX_GPIO=y
arm: boundary_defconfig: add CONFIG_MXC4005=m
arm: boundary_defconfig: add CONFIG_NFC_NXP_PN5XX=m
arm: boundary_defconfig: add CONFIG_LEDS_IS31FL32XX=m
arm: boundary_defconfig: add CONFIG_VF610_ADC=m
arm: boundary_defconfig: s/CONFIG_SENSORS_MAG3110/CONFIG_MAG3110

Signed-off-by: Troy Kisky <troy.kisky@boundarydevices.com>

add subdev vadc and ov5640_mipi drivers
add GPIO backlight driver
add i.MX7 support
add SAS configuration
add qcacld support
add IPU prefetch config for 6QP
remove CONFIG_SOC_IMX6UL
add lm75 temp sensor module
add TI ADC081C module
add FTP628 config
add TI_ADS7924 module
add HID_MULTITOUCH
add TI LMP900xx module
add TUSB320 config
enable syscon poweroff option
add LM3643 flashlight driver
use mainline driver for rv4162
fix IWL config and savedefconfig
add missing options
add missing ARM_PSCI option
savedefconfig with new media drivers

arm: boundary_defconfig: add pci and security options
arm: boundary_defconfig: fix hdmi audio driver

Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>

enable Universal TUN/TAP device driver
extend squashfs compression options needed for ubuntu-core
Add support for Qualcomm WWAN LTE/3G devices
add iptables NAT support and netfilter nf_tables support
add configs for Docker
armhf: boundary_defconfig: add System Blacklist Keyring, Ubuntu requirement
armhf: boundary_defconfig: add ion support
armhf: boundary_defconfig: add SERIAL_DEV_BUS and BT_HCIUART_LL for bluetooth and TiWi-BLE support

Signed-off-by: Laci Tele <laci@boundarydevices.com>

arm: boundary_defconfig: make CONFIG_BT_HCIUART=y

When loaded as module, hciattach fails on some i.MX6 bases boards, so
make it set to y.

boundary_defconfig: add CONFIG_KPROBES=y

Needed for lttng-modules in yocto hardknott + 5.10 kernel, as per the
compilation error:

LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0

Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>