ENGR00266342-2 dts: imx6qdl-sabresd: move epdc to board specific dts file
epdc is only exist on mx6dl/solo, put it in common sabresd board dts file
will cause imx6q sabresd building to fail.

$ make ARCH=arm CROSS_COMPILE=arm-fsl-linux-gnueabi- uImage -j8
LOADADDR=0x10800000 dtbs
  CHK     include/linux/version.h
  DTC     arch/arm/boot/imx6q-sabresd.dtb
ERROR (phandle_references): Reference to non-existent node or
label "pinctrl_epdc_0"

ERROR: Input tree has errors, aborting (use -f to force output)
make[1]: *** [arch/arm/boot/imx6q-sabresd.dtb] Error 2
make: *** [dtbs] Error 2
make: *** Waiting for unfinished jobs....

Moving epdc to the specific imx6dl-sabresd.dts to fix this issue.

BTW, there's a lot SoC specific properties in epdc node could be put in
the board independant soc dtsi, but i'm not going to fix it in this patch.
That could be fixed latter by the module owner.

Signed-off-by: Dong Aisheng <b29396@freescale.com>