drm: bridge: it6161: add missing gpio consumer header
Fix it6161.c:2810:24: error: implicit declaration of function
'devm_gpiod_get_optional'.

Signed-off-by: Ricardo Salveti <ricardo@foundries.io>
Acked-by: Jason Liu <jason.hui.liu@nxp.com>