MA-18837-5 defconfig: Disable CONFIG_IMX_SENTNL_MU to fix build error
CONFIG_IMX_SENTNL_MU depends on IMX_MBOX, it will be selected
as "m" using imx8 gki fragment.
But this driver is not ready to be built as module
with below build error:
  ERROR: modpost: "soc_device_to_device" [drivers/firmware/imx/sentnl_mu.ko] undefined!

The driver config name has been changed from CONFIG_IMX_S400_API
to CONFIG_IMX_SENTNL_MU.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: Id531c7852625fbf1204370bb33f31a6adefdeb14