MA-22440 pmdomain: arm: Remove scmi_perf_domain.c
In the community drivers/firmware/arm_scmi/scmi_perf_domain.c has been
moved to drivers/pmdomain/arm/scmi_perf_domain.c in order to avoid
following build error.

error: the following would cause module name conflict:
  drivers/pmdomain/arm/scmi_perf_domain.ko
  drivers/firmware/arm_scmi/scmi_perf_domain.ko

Change-Id: Iffb1c4d269522d6c5d4c2f7efed31fc499d0dbe4
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>