MA-22127 Revert "net: add 25GBase-KR-S and 25GBase-CR-S to ethtool link mode UAPI"
The patch is only needed on a Layerscape platform and break the ABI, so
revert it.

Unable to fix by CONFIG_IMX_GKI_FIX due to encountering the following error:
error: include/uapi/linux/ethtool.h: leak CONFIG_IMX_GKI_FIX to user-space

This reverts commit 1c810dd48099d3f2f591dafa32c68649439499c5.

Change-Id: Ic7ef51c9646d36f9c8dd1d957a70581a81e1c685