LF-9966-2 media: Mixel CSI2: fix build error due to API change
drivers/staging/media/imx/imx8-mipi-csi2.c:289:37: error: field 'asd' has incomplete type
  289 |         struct v4l2_async_subdev    asd;
      |                                     ^~~

caused by
commit adb2dcd5f2d4 ("media: v4l: async: Rename v4l2_async_subdev as v4l2_async_connection")

Signed-off-by: Robby Cai <robby.cai@nxp.com>