MA-19046 clk: imx8mm: Support clk-imx8mm driver built as module
Fix below two build errors:
1> drivers/clk/imx/clk-imx8mm.c:742:1: error: redefinition of '__inittest'
    late_initcall(pll_debug_init);

2> WARNING: modpost: drivers/clk/imx/clk-imx8mm.o(.text+0x2eb4):
Section mismatch in reference from the function imx8mm_clocks_probe() to the function .init.text:imx_clk_init_on()
The function imx8mm_clocks_probe() references
the function __init imx_clk_init_on().
This is often because imx8mm_clocks_probe lacks a __init
annotation or the annotation of imx_clk_init_on is wrong.

ERROR: modpost: Section mismatches detected.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: I6cda6abec64d6c09dc2473485ce3f0b1a39041ff