GENIO: soc: mediatek: mmsys: Drop unused variable
The ret variable in the mtk_mmsys_cross_sys_unprepare() function is
unused, which if flagged by a compiler warning:

drivers/soc/mediatek/mtk-mmsys.c: In function ‘mtk_mmsys_cross_sys_unprepare’:
drivers/soc/mediatek/mtk-mmsys.c:325:16: error: unused variable ‘ret’ [-Werror=unused-variable]
  325 |         int i, ret;
      |                ^~~

Drop it to get rid of the warning.

Change-Id: I71486c9767d607b314a7b14faa827fdfe13b6eea
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>