MA-20763-6 drm: imx: Fix drm build error
error:
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:176:23: error: variable 'encoder' is uninitialized when used here [-Werror,-Wuninitialized]
                drm_encoder_cleanup(encoder);
drivers/gpu/drm/imx/mhdp/cdns-mhdp-imxdrv.c:163:29: note: initialize the variable 'encoder' to silence this warning
        struct drm_encoder *encoder;

drivers/gpu/drm/imx/sec_mipi_dsim-imx.c:452:3: error: implicit declaration of function 'sec_dsim_of_put_resets' [-Werror,-Wimplicit-function-declaration]
                sec_dsim_of_put_resets(dsim_dev);

Remove sec_dsim_of_put_resets(dsim_dev); directly because
it is removed in the following patch:
	9020454bf708 MA-20247-4 drm/imx: sec_mipi_dsim-imx: Get and control reset lines separately

Change-Id: I950190d15c8cf926b868b4cace709b7a9b79aa46
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>