boundary_defconfig: add CONFIG_KPROBES=y
Needed for lttng-modules in yocto hardknott + 5.10 kernel, as per the
compilation error:

LTTng-modules requires CONFIG_KPROBES on kernels >= 5.7.0

Signed-off-by: Chris Dimich <Chris.Dimich@boundarydevices.com>