ASoC: dpcm: fixed compilation warnings
As per commit 435ffb76f8b3 ("ASoC: dpcm: rework runtime stream merge")
made changes to fix the compilation error.

sound/soc/soc-pcm.c: In function ‘dpcm_set_fe_runtime’:
sound/soc/soc-pcm.c:1887:15: error: implicit declaration of function ‘dpcm_runtime_base_format’; did you mean ‘dpcm_runtime_merge_format’? [-Werror=implicit-function-declaration]
  u64 format = dpcm_runtime_base_format(substream);
               ^~~~~~~~~~~~~~~~~~~~~~~~
               dpcm_runtime_merge_format
sound/soc/soc-pcm.c:1893:3: error: too many arguments to function ‘dpcm_init_runtime_hw’
   dpcm_init_runtime_hw(runtime, &cpu_dai_drv->capture, format);
   ^~~~~~~~~~~~~~~~~~~~
sound/soc/soc-pcm.c:1678:13: note: declared here
 static void dpcm_init_runtime_hw(struct snd_pcm_runtime *runtime,
             ^~~~~~~~~~~~~~~~~~~~
At top level:
sound/soc/soc-pcm.c:1784:13: warning: ‘dpcm_runtime_merge_rate’ defined but not used [-Wunused-function]
 static void dpcm_runtime_merge_rate(struct snd_pcm_substream *substream,
             ^~~~~~~~~~~~~~~~~~~~~~~
sound/soc/soc-pcm.c:1733:13: warning: ‘dpcm_runtime_merge_chan’ defined but not used [-Wunused-function]
 static void dpcm_runtime_merge_chan(struct snd_pcm_substream *substream,
             ^~~~~~~~~~~~~~~~~~~~~~~
sound/soc/soc-pcm.c:1692:13: warning: ‘dpcm_runtime_merge_format’ defined but not used [-Wunused-function]
 static void dpcm_runtime_merge_format(struct snd_pcm_substream *substream,
             ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/soc-pcm.o' failed
make[2]: *** [sound/soc/soc-pcm.o] Error 1
scripts/Makefile.build:546: recipe for target 'sound/soc' failed
make[1]: *** [sound/soc] Error 2

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>