CHROMIUM: drm/mediatek: Remove usage of cmdq_cb_status
Remove usage of error status "cmdq_cb_status". It's removed in UPSTREAM
CL:3244691. Otherwise, there's build error after applied the CL.

(1)
/mnt/host/source/src/third_party/kernel/v5.10/drivers/media/platform/mtk-mdp3/mtk-mdp3-cmdq.c:390:18:
error: use of undeclared identifier 'CMDQ_CB_ERROR'; did you mean
'CMDQ_CODE_EOC'?
        if (data.sta == CMDQ_CB_ERROR) {
                        ^~~~~~~~~~~~~
                        CMDQ_CODE_EOC
/mnt/host/source/src/third_party/kernel/v5.10/include/linux/mailbox/mtk-cmdq-mailbox.h:61:2:
note: 'CMDQ_CODE_EOC' declared here
        CMDQ_CODE_EOC = 0x40,
        ^
1 error generated.

(2)
  CC [M]  drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.o
/mnt/host/source/src/third_party/kernel/v5.10/drivers/media/platform/mtk-isp/isp_50/dip/mtk_dip-sys.c:233:18:
error: use of undeclared identifier 'CMDQ_CB_NORMAL'
        if (data.sta != CMDQ_CB_NORMAL) {
                        ^
1 error generated.

BUG=b:188614535
TEST=emerge-cherry sys-kernel/chromeos-kernel-5_10

Signed-off-by: jason-jh.lin <jason-jh.lin@mediatek.com>
Change-Id: I31e560043d1ebce8e9cf6f4bdf8fc6ff277b6270
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/3244702
Reviewed-by: Tzung-Bi Shih <tzungbi@chromium.org>
Tested-by: Tzung-Bi Shih <tzungbi@chromium.org>
Commit-Queue: Tzung-Bi Shih <tzungbi@chromium.org>