MA-18837-4 defconfig: Disable CONFIG_IMX_S400_API to fix build error
IMX_S400_API depends on IMX_MBOX, it will be selected
as "m" using imx8 gki fragment.
But this driver is not ready to be built as module
with below build error:
  ERROR: modpost: "soc_device_to_device" [drivers/firmware/imx/s400-api.ko] undefined!

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: I2c8a1999ef8b78dc33bafbf0b998a28ed515b983