MLK-24874-4: include: uapi: tsn: fix the UAPI_HEADER_TEST failure
Enable CONFIG_UAPI_HEADER_TEST turns out the following build issues:

 HDRTEST usr/include/linux/tsn.h
In file included from <command-line>:32:0:
./usr/include/linux/tsn.h:384:2: error: unknown type name ‘__u8’
  __u8 admin_state;
  ^~~~
./usr/include/linux/tsn.h:390:2: error: unknown type name ‘__u32’
  __u32 hold_advance;
  ^~~~~
./usr/include/linux/tsn.h:397:2: error: unknown type name ‘__u32’
  __u32 release_advance;
  ^~~~~
./usr/include/linux/tsn.h:403:2: error: unknown type name ‘__u8’
  __u8 preemption_active;
  ^~~~
./usr/include/linux/tsn.h:412:2: error: unknown type name ‘__u8’
  __u8 hold_request;
  ^~~~
./usr/include/linux/tsn.h:426:2: error: unknown type name ‘__u8’
  __u8 delta_bw; /* percentage, 0~100 */
  ^~~~
./usr/include/linux/tsn.h:427:2: error: unknown type name ‘__u32’
  __u32 idleslope;
  ^~~~~
./usr/include/linux/tsn.h:428:2: error: unknown type name ‘__s32’
  __s32 sendslope;
  ^~~~~
./usr/include/linux/tsn.h:429:2: error: unknown type name ‘__u32’
  __u32 maxframesize;
  ^~~~~

The fix is to add the necessary header file into the tsn.h file

Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>
(cherry picked from commit 328bf99d8b42aca38538b6122878c7a9da9234d0)
Change-Id: I5320cbf529130998ec5668c4307e768ed157303b