MLK-11660: spi: spi-imx: fix building error
fix building error by d5150a37c14:

drivers/spi/spi-imx.c: In function 'spi_imx_can_dma':
drivers/spi/spi-imx.c:211:3: error: expected ')' before 'return'
   return true;
      ^
      drivers/spi/spi-imx.c:213:1: error: expected expression before '}' token
      4.1build error

Signed-off-by: Robin Gong <b38343@freescale.com>
(cherry picked from commit 2e1aff2df420dc5181b6f3f98652e1e044d8ef6c)