LF-1011-24 media: mxc: ov5640_mipi_v2: fix build due to i2c_new_dummy removed
API changed since:
2c2f00ab1641 ("i2c: remove i2c_new_dummy() API")

../drivers/media/platform/mxc/capture/ov5640_mipi_v2.c: In function ‘ov5640_update_slave_id’:
../drivers/media/platform/mxc/capture/ov5640_mipi_v2.c:524:3: error: implicit declaration of function ‘i2c_new_dummy’ [-Werror=implicit-function-declaration]
  524 |   i2c_new_dummy(tmp_client->adapter, DEFAULT_SCCB_ID >> 1);
      |   ^~~~~~~~~~~~~
../drivers/media/platform/mxc/capture/ov5640_mipi_v2.c:523:21: warning: assignment to ‘struct i2c_client *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  523 |  sensor->i2c_client =
      |                     ^

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>