MA-22955-1 Revert "LF-13605: sync bounce buffer"
This patch calls a symbol swiotlb_find_pool that has not been exported
by the kernel, leading to the following build error.

ERROR: modpost: "swiotlb_find_pool" [drivers/mxc/vpu/wave6/wave6.ko] undefined!

This patch is only useful in XEN. The host for XEN is Linux, and Android
acts as the guest. Therefore, this code is not needed and should be
reverted. Additionally, after IOMMU is enabled, this patch will also
need to be removed.

This reverts commit 820ff4509686a7d8bd8ead8ff8fb9ae10f36f15f.

Change-Id: I438fbf52dda1833843bf6acda88bf0b26f371de4