LF-1011-16 ASoC: fsl: pcm-dma-v2: drop snd_soc_pcm_lib_ioctl
This ioctl was removed since:
e91f134c83b1 ("ASoC: sh: Drop superfluous ioctl PCM ops")

../sound/soc/fsl/imx-pcm-dma-v2.c:272:12: error: ‘snd_soc_pcm_lib_ioctl’ undeclared here (not in a function); did you mean ‘snd_pcm_lib_ioctl’?
  272 |  .ioctl  = snd_soc_pcm_lib_ioctl,
      |            ^~~~~~~~~~~~~~~~~~~~~
      |            snd_pcm_lib_ioctl

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>