ASoC: fsl_asrc: fixed compilation error
In commit 7f1106616ab6 ("ASoC: fsl: asrc: replace platform to component")

platform is replaced with component. So, removing the following code to
fix the compilation error.

sound/soc/fsl/fsl_asrc.c: In function ‘fsl_asrc_probe’:
sound/soc/fsl/fsl_asrc.c:926:8: error: implicit declaration of function ‘devm_snd_soc_register_platform’; did you mean ‘devm_snd_soc_register_card’? [-Werror=implicit-function-declaration]
  ret = devm_snd_soc_register_platform(&pdev->dev, &fsl_asrc_platform);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        devm_snd_soc_register_card
sound/soc/fsl/fsl_asrc.c:926:52: error: ‘fsl_asrc_platform’ undeclared (first use in this function); did you mean ‘fsl_asrc_pair’?
  ret = devm_snd_soc_register_platform(&pdev->dev, &fsl_asrc_platform);
                                                    ^~~~~~~~~~~~~~~~~
                                                    fsl_asrc_pair
sound/soc/fsl/fsl_asrc.c:926:52: note: each undeclared identifier is reported only once for each function it appears in
  CC      net/can/bcm.o
  CC      fs/quota/netlink.o
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target 'sound/soc/fsl/fsl_asrc.o' failed
make[3]: *** [sound/soc/fsl/fsl_asrc.o] Error 1

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>
Signed-off-by: Srikanth Krishnakar <Srikanth_Krishnakar@mentor.com>