MA-20197-4 uapi: dma-buf-imx: use __u64 instead of uint64_t
Enable CONFIG_UAPI_HEADER_TEST turns on the following build issue:

./usr/include/linux/dma-buf-imx.h:23:2: error: unknown type name '__u32'
        __u32 dmafd;
        ^
./usr/include/linux/dma-buf-imx.h:24:2: error: unknown type name
'uint64_t'
        uint64_t phys;
        ^

To fix it, use __u64 instead of uint64_t and include linux/types.h.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>