Revert "arm64: KVM: define HYP and Stage-2 translation page flags"
This reverts commit 3d20c4a5ebffee4924c20972aea3e68e22ec8ec9 to resolve
the following build error:

In file included from arch/arm64/kvm/handle_exit.c:26:0:
arch/arm64/include/asm/kvm_mmu.h: In function ‘kvm_set_s2pmd_writable’:
arch/arm64/include/asm/kvm_mmu.h:122:19: error: ‘PMD_S2_RDWR’ undeclared (first use in this function)
  pmd_val(*pmd) |= PMD_S2_RDWR;
                   ^

Signed-off-by: Alex Shi <alex.shi@linaro.org>