brcmfmac: Fix compilation error
As per 'commit 2d6edad4b2da ("brcmfmac: remove duplicate pointer variable
from brcmf_sdio_firmware_callback()")', make changes to fix the
compilation error.

drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c: In function ‘brcmf_sdio_firmware_callback’:
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4112:11: error: ‘sdiodev’ undeclared (first use in this function); did you mean ‘sdiod’?
   switch (sdiodev->func0->device) {
           ^~~~~~~
           sdiod
drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c:4112:11: note: each undeclared identifier is reported only once for each function it appears in

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>