LF-1162-2 Revert "dmaengine: imx-sdma: fix context cache"
This reverts commit d288bddd8374e0a043ac9dde64a1ae6a09411d74.

This patch is invalid since local commit:
a03180986b79 ("Revert "dmaengine: imx-sdma: refine to load context only once"")

Otherwise, met build break as follows:
../drivers/dma/imx-sdma.c: In function ‘sdma_free_chan_resources’:
../drivers/dma/imx-sdma.c:1533:7: error: ‘struct sdma_channel’ has no member named ‘context_loaded’
 1533 |  sdmac->context_loaded = false;
      |       ^~

Module onwer could follow for a fine tuned solution.

Signed-off-by: Dong Aisheng <aisheng.dong@nxp.com>