mips: re-order DT init scan
Netlogic XLP needs early DT scan and was calling early_init_devtree to
do so. The result was 2 calls to do DT scan. There does not appear to
be any reason the DT scan cannot be earlier on all platforms and the
XLP call can be removed. This fixes build breakage due to removing
early_init_devtree.

arch/mips/built-in.o: In function `plat_mem_setup':
(.init.text+0x5b0): undefined reference to `early_init_devtree'

It appears this was caused by f75813c0127bbef41ac3152f64a72ba212a5514c
[mips: use early_init_dt_scan] which removes the early_init_devtree
function but doesn't the call in arch/mips/netlogic/xlp/setup.c.

Reported-by: Ralf Baechle <ralf@linux-mips.org>
Signed-off-by: Rob Herring <rob.herring@calxeda.com>