drm/mediatek: conditionally add mtk_dp to driver list
Some platforms (like mt8183) who don't have DPTX should not have to
enable CONFIG_MTK_DPTX_SUPPORT. If we don't add this config, the
following link error is observed:
aarch64-poky-linux-ld.bfd: drivers/gpu/drm/mediatek/mtk_drm_drv.o:(.rodata+0x48): undefined reference to `mtk_dp_driver'

Fix it by guarding with IS_REACHABLE()

Fixes: 6097cd05ab1b ("drm/mediatek: Add mt8195 Embedded DisplayPort driver")
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>