can: flexcan: Fix compilation error
As per 'commit 88462d2a7830 ("can: flexcan: Remodel FlexCAN register r/w
APIs for big endian FlexCAN controllers.")', make changes to fix the
compilation error.

drivers/net/can/flexcan.c: In function ‘flexcan_set_bittiming’:
drivers/net/can/flexcan.c:1135:3: error: implicit declaration of function ‘flexcan_write’; did you mean ‘flexcan_write_le’? [-Werror=implicit-function-declaration]
   flexcan_write(reg, &regs->fdcbt);
   ^~~~~~~~~~~~~
   flexcan_write_le
In file included from drivers/net/can/flexcan.c:12:
drivers/net/can/flexcan.c:1146:7: error: implicit declaration of function ‘flexcan_read’; did you mean ‘flexcan_read_le’? [-Werror=implicit-function-declaration]
       flexcan_read(&regs->ctrl),
       ^~~~~~~~~~~~
./include/linux/netdevice.h:4636:46: note: in definition of macro ‘netdev_dbg’
   netdev_printk(KERN_DEBUG, __dev, format, ##args); \
                                              ^~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:303: recipe for target 'drivers/net/can/flexcan.o' failed

Signed-off-by: Vipul Kumar <vipul_kumar@mentor.com>