MA-20974-2 ASoC: fsl_xcvr: Add void in fsl_xcvr_get_attr_grp
Fix below error reported by clang:
sound/soc/fsl/fsl_xcvr_sysfs.c:106:52: error:
a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
const struct attribute_group *fsl_xcvr_get_attr_grp()
                                                   ^
                                                    void

Change-Id: I80280ee794587d97475ef6403a3d6474efa8de1b
Signed-off-by: Jindong Yue <jindong.yue@nxp.com>