MA-22434-2 iommu/arm-smmu-v3: Fix build error
error log:

drivers/iommu/arm/arm-smmu-v3/arm-smmu-v3.c:2726:3: error: call to
undeclared function 'arm_smmu_write_msi_msg'; ISO C99 and later do not
support implicit function declarations [-Wimplicit-function-declaration]
arm_smmu_write_msi_msg(desc, &msg);

arm_smmu_write_msi_msg is called by arm-smmu-v3.c, so it needs to be
changed.

Change-Id: I0e64d0f2e71bb9d820cd7d5bb4672731a55523f2
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>