MA-16809 dts: change 8qxp default dts as imx8qxp-mek-ov5640-rpmsg.dts
BSP has added imx8qxp-mek-ov5640-rpmsg.dts, which
includes imx8x-mek-rpmsg.dtsi.

This patch fixes below dts build error:
Error: arch/arm64/boot/dts/freescale/imx8x-mek-rpmsg.dtsi:6.15-24 Label or path cm40_i2c not found
Error: arch/arm64/boot/dts/freescale/imx8x-mek-rpmsg.dtsi:7.15-20 Label or path i2c1 not found
scripts/Makefile.lib:285: recipe for target 'arch/arm64/boot/dts/freescale/imx8qxp-mek-ov5640-rpmsg.dtb' failed

The reason is imx8x-mek-rpmsg.dtsi is included twice.

Signed-off-by: Jindong <jindong.yue@nxp.com>
Change-Id: Ia510532a8f4737ed0e4d4d9baa2aea9b415b34ab