MA-21172 Revert "Revert "tty: serial: fsl_lpuart: adjust SERIAL_FSL_LPUART_CONSOLE config dependency""
Remove the limitation of SERIAL_FSL_LPUART=y,
as we may need enable this console while SERIAL_FSL_LPUART=m.

The situation in 4d2304d8f779 we do not encounter now:

    This results in a link error of

    ld: drivers/tty/serial/earlycon.o: in function `parse_options':
    drivers/tty/serial/earlycon.c:99: undefined reference to `uart_parse_earlycon'

    When the config is in this state

    CONFIG_SERIAL_CORE=m
    CONFIG_SERIAL_CORE_CONSOLE=y
    CONFIG_SERIAL_EARLYCON=y
    CONFIG_SERIAL_FSL_LPUART=m
    CONFIG_SERIAL_FSL_LPUART_CONSOLE=y

This reverts commit 4d2304d8f77974209f7dc82f6fc50d94599bf1fe.

Change-Id: Ifd5c31f89af87dbbda0b7eb7160832535e60b2df