MA-20197-5 uapi: mxcfb: use __s[32,64] instead of int[32,64]_t
Enable CONFIG_UAPI_HEADER_TEST turns on the following build issue:

./usr/include/linux/mxcfb.h:172:23: warning: // comments are not allowed
in this language [-Wcomment]
        unsigned long  phys; // represents dma buf.
                             ^
./usr/include/linux/mxcfb.h:183:2: error: unknown type name 'int32_t'
        int32_t fence_fd;
        ^
./usr/include/linux/mxcfb.h:185:2: error: unknown type name 'int64_t'
        int64_t fence_ptr;
        ^

To fix it, use __s[32,64] instead of int[32,64]_t, and use
standard C style comments (/* ... */).

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>