Revert "CHROMIUM: Mark mt7925 and Mediatek SoC Ethernet drivers as broken"
This reverts commit e79fded75c0b237eac0b77934194c7c1fb059133.

Reason for revert: fix for MT7925 has been merged.

Original change's description:
> CHROMIUM: Mark mt7925 and Mediatek SoC Ethernet drivers as broken
>
> drivers/net/wireless/mediatek/mt76/mt7925/main.c:382:9: error: implicit declaration of function ‘mt76_wcid_init’; did you mean ‘mt76_mmio_init’? [-Werror=implicit-function-declaration]
> drivers/net/ethernet/mediatek/mtk_wed.c:88:37: error: invalid application of ‘sizeof’ to incomplete type ‘struct mtk_wed_bm_desc’
> drivers/net/ethernet/mediatek/mtk_wed.c:618:61: error: invalid application of ‘sizeof’ to incomplete type ‘struct mtk_wed_bm_desc’
> drivers/net/ethernet/mediatek/mtk_wed.c:649:29: error: invalid use of undefined type ‘struct mtk_wed_bm_desc’
> drivers/net/ethernet/mediatek/mtk_wed.c:651:29: error: increment of pointer to an incomplete type ‘struct mtk_wed_bm_desc’
> drivers/net/ethernet/mediatek/mtk_wed.c:709:66: error: invalid application of ‘sizeof’ to incomplete type ‘struct mtk_wed_bm_desc’
>
> The CL introducing mt76_wcid_init() was not committed, breaking the build.
> Similar, NET_MEDIATEK_SOC is broken, presumably for the same reason.
>
> Mark the drivers as broken until the problems are fixed.
>
> BUG=b:338656798, b:178754244, b:337131500
> TEST=Test builds pass
>
> Change-Id: I394c0952fe3229f0ede5fddb45955f731fdb5641
> Disallow-Recycled-Builds: test-failures
> Signed-off-by: Guenter Roeck <groeck@chromium.org>
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5516602
> Reviewed-by: David Ruth <druth@chromium.org>
> Reviewed-by: Jintao Lin <jintaolin@chromium.org>

BUG=b:338656798, b:178754244, b:337131500

Change-Id: Iff43a9782e6b77d5232479e026bfc46c4a140e20
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/kernel/+/5523906
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Guenter Roeck <groeck@chromium.org>