ASoC: SOF: imx8m: Fix compilation error
sound/soc/sof/imx/imx8m.c: In function imx8m_reset:

sound/soc/sof/imx/imx8m.c:240:25: error: struct imx8m_priv has no
member named regmap_audiomixâ

  240: regmap_update_bits(priv->regmap_audiomix, AudioDSP_REG2,

We changed in the last moment the filed for audiomix regmap
but did not update all over the places.

Signed-off-by: Daniel Baluta <daniel.baluta@nxp.com>