MA-20012 Fix build error when export new symbols
Because the argument type is volatile, but the parameter is
not, you need both to be volatile.

test:

when build nxp kernel in aosp kernel repo, we will meet the build error.
/opt/android/kernel_symbols_build/gki-imx/common/drivers/mxc/hantro/hantrodec.c:402:48:
error: passing 'volatile u8 *' (aka 'volatile unsigned ch
ar *') to parameter of type 'u8 *' (aka 'unsigned char *') discards qualifiers
[-Werror,-Wincompatible-pointer-types-discards-qualifiers]
trusty_ctrlblk_write(&hantrodec_data, 0, 0x3, iobase);  //VPUMIX G1/G2 block soft reset  control

BUILD_CONFIG=common/build.config.imx build/build_abi.sh

Change-Id: I055e65c65927fb3171aa4b8fd536106aaf252913
Signed-off-by: zhai.he <zhai.he@nxp.com>