MA-16768 fix build error when CONFIG_BLK_DEV_DM is not set
it have below build error when CONFIG_BLK_DEV_DM is set m or not set.
/home/sanshan/imx_android10.0_lf-5.4/vendor/nxp-opensource/kernel_imx/init/do_mounts.c:592:3: error: implicit declaration of function
      'wait_dm_device_ready' [-Werror,-Wimplicit-function-declaration]

Change-Id: I159c233e4228fd0738b42b2bf4b809272a9aa63d
Signed-off-by: zhang sanshan <pete.zhang@nxp.com>