LF-3950-1 Revert "LF-3950 dts: arm64: imx8m: correct root dts cma alloc ranges"
This reverts commit 86d098bc64e4a77b204c762b546c388ced9a238e.

Reason to revert:
  To configure cma by command line, Android has deleted
"linux,cma" node. This patch will cause build error:
  imx8mm-evk-root.dts:75.1-30 Label or path /reserved-memory/linux,cma not found
  FATAL ERROR: Syntax error parsing input tree

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: Ibe9fda9bb63bd00bbe766c47a5749813f0857e89