MA-19640-4  ASoC: rpmsg-pcm512x: Fix return type of rpmsg_pcm512x_i2c_remove
The return value of .remove is changed from int to void, the
build encounters the following error：

sound/soc/codecs/rpmsg_pcm512x_i2c.c:75:13: error: incompatible function pointer types initializing 'void (*)(struct i2c_client *)'
with an expression of type 'int (struct i2c_client *)'
[-Wincompatible-function-pointer-types] .remove = rpmsg_pcm512x_i2c_remove, ^~~~~~~~~~~~~~~~~~~~~~~~

Change-Id: I3d9a1619b985b9c6f4c4f0eb7bcf4da87725294c
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>