MA-19811-10 build.config.imx: Enable HAVE_IMX_BUSFREQ
CONFIG_HAVE_IMX_BUSFREQ is disabled in imx8ulp_gki.fragment.
We need to enable it when generate imx symbol lists to fix
below build error:
  drivers/soc/imx/busfreq-imx8mq.c:339:6: error: redefinition of 'request_bus_freq'
  include/linux/busfreq-imx.h:58:20: note: previous definition is here

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Change-Id: I3836a7c39756e0dc912c82a909c23cf24db81fe9